### ISSUE TITLE
Infantry get stucked in japanese tent

### ISSUE THREAD

**Issue by shibumi** [spring1944/spring1944#348] opened 2019-06-21 12:47 UTC
It happens quite often that single infantry units get stucked in the tent when they get build.. after a match with 30min there are over 10 units in the tent stucked and the tent cant produce anymore infantry..

**Comment by simonpuchert** [comment] 2019-06-23 00:17
Aside from spawn-points, there is a more general issue with the pathfinding. It is actually quite easy to get units stuck in trees, houses and, of course, player-made buildings. Most of the time one can recover by just reversing out, but sometimes the unit is stuck for good.
I don't know how that could be fixed, though. Maybe one could try pushing the units off the obstacle (some sort of forced movement) or make them "semi-permeable" (I think 0 A.D. does that). But that might be an issue for Spring itself.

**Comment by shibumi** [comment] 2019-06-23 01:11
well this has nothing to do with path finding.. this units get stucked instantly when they spawn.

**Comment by sanguinariojoe** [comment] 2019-06-23 11:29
spring 104?

**Comment by simonpuchert** [comment] 2019-06-23 16:25
@sanguinariojoe I could reproduce a similar issue, although I don't know if it's related to what @shibumi found.
Using Spring 104.0 with QTPFS I could not get units to be stuck upon spawning. However, if you place the rally point to the opposite side of the tent exit, units will walk out, some will walk back inside, and get stuck there.
As these units are often quite easily recoverable by sending them out through the exit, I have my doubts that it's the same problem, but since I don't know the secret recipe for getting units stuck it's the closest thing I could come up with.

Also, units getting stuck is always related to pathfinding. "Stuck" basically means "unable to find a path out". Pathfinding might not be the reason the unit got there in the first place, but if these situations can't be avoided reliably, it might be the best solution to implement a somewhat reasonable way to handle them.

**Comment by shibumi** [comment] 2019-06-25 20:17
@sanguinariojoe yes spring 104

**Comment by FLOZi** [comment] 2019-08-30 20:33
Please test with 6c5187ad6

**Comment by sanguinariojoe** [comment] 2020-09-30 11:13
Heavily related with https://github.com/spring1944/spring1944/issues/352 . I will close this PR and continue discussing there

**Closed by sanguinariojoe** 2020-09-30 11:13 UTC
