### ISSUE TITLE
Loading a tank back

### ISSUE THREAD

**Issue by jal76** [spring1944/spring1944#354] opened 2019-10-12 23:11 UTC
In engine 104+ i loaded a tank back to boat-transport and the game crashed .
https://justpaste.it/27dw2

**Comment by FLOZi** [comment] 2020-06-20 11:38
Engine 1408, I had many crashes with transports before switching to 1510. Do you recall which boat and tank it was? Map is Downpour 1.1. If I can't reproduce in 1510 I'll close this as we can't run the stacktrace anyway.

**Comment by jal76** [comment] 2020-06-20 15:53
it happened to 2 times, 1 time with italian, another with british tank transport

**Comment by FLOZi** [comment] 2020-06-20 16:12
Can't replicate on 1510 with either itamz or gbrlct, closing for now.

**Closed by FLOZi** 2020-06-20 16:12 UTC
