### ISSUE TITLE
Spammer BOT died.

### ISSUE THREAD

**Issue by frju365** [spring1944/spring1944#250] opened 2017-08-21 14:33 UTC
The units of the spammer bot, when they are blocked, died after a few minutes and keep trying to pass. I made a wall and every units died on them. But apparently they died even if nothing blocks them. I've commando who died just before entering in my base and nothing shot them, same for rifle, and same for US Sea-Tank.

Replays : https://think.nsupdate.info/s44/autohosts/demos/WorldAtWarII_rapid2/20170821_151216_FolsomDamFlooded_103.sdfz

**Comment by specing** [comment] 2018-01-10 00:18
AFAIK this is by design. Maybe one day someone will teach it to clear obstacles.

**Comment by sanguinariojoe** [comment] 2020-09-30 14:19
Then I'm closing this issue

**Closed by sanguinariojoe** 2020-09-30 14:19 UTC
