### ISSUE TITLE
flag.lua bug

### ISSUE THREAD

**Issue by jal76** [spring1944/spring1944#220] opened 2017-05-08 20:03 UTC
it happens rare, but it causes desybc sometimes.

 http://paste.springfiles.com/view/3b70e57a

**Comment by kanatohodets** [comment] 2017-05-08 21:05
Likely reproducible by having someone who picked random team capture a flag on a map with wind. 

The first log message (`[flag script] Error: teamSide contains: random team (gm) for teamID: 3`) will probably happen any time a random side person caps a flag. 

The only reason I'd hesitate about that theory is that it first happened 26 minutes into the game, which seems awfully late for any team to first be capping flags.

**Comment by yuritch** [comment] 2017-05-10 09:06
It's as if something set the team text back to 'randon team' midgame. Because it does not happen at game start, and we've played lots of games with random team players without this bug.

**Comment by yuritch** [comment] 2017-05-10 09:33
Interesting. Can it be that side picker UI was still shown after game start, and someone clicked on a random side icon there? Maybe that's possible by deactivating/reactivating the widget?

From what I see in the gadget code, that would set side to 'random team (gm)' and cause the bug.

**Comment by yuritch** [comment] 2017-05-10 09:48
Added some code to change random side to a real side if it somehow comes in. Let's see if that helps.

**Comment by jal76** [comment] 2017-05-11 15:16
http://paste.springfiles.com/view/7ae90bb4

shibumi and me started with nobase

**Comment by yuritch** [comment] 2017-05-11 22:00
Made a fix. I think this should do it.

**Comment by buumi** [comment] 2017-05-12 16:48
This time everyone spawned without a base. https://think.nsupdate.info/s44/autohosts/demos/WorldAtWarII_rapid2/20170512_184154_1944_Kiev_V4_103.sdfz

**Comment by jal76** [comment] 2017-05-12 16:49
It didnt fix it, and all 6 players were without base, there is a texture bug too-

**Comment by jal76** [comment] 2017-05-12 16:51
its broken actually

**Comment by jal76** [comment] 2017-05-12 17:59
sorry, had to revert it

**Comment by kanatohodets** [comment] 2017-05-12 19:51
Fixed in 206869b100a

**Closed by kanatohodets** 2017-05-12 19:51 UTC
