### ISSUE TITLE
rifles firing uphill don't impact targets occasionally

### ISSUE THREAD

**Issue by kanatohodets** [spring1944/spring1944#37] opened 2014-07-27 22:36 UTC
perhaps something to do with the intensity fade out

**Comment by ashdnazg** [comment] 2015-01-26 21:10
This needs to be reproduced in development version. (I couldn't)

**Comment by ashdnazg** [comment] 2015-02-04 01:00
Please verify that this was fixed

**Comment by kanatohodets** [comment] 2015-04-09 08:47
https://springrts.com/mantis/view.php?id=4661 references something similar. sounds like 99.0 will resolve this, burnblow or not. It does still happen in latest S44 git (I saw it in a few recent games -- inf up on a hill not getting hit; shots passing through them).

**Comment by ashdnazg** [comment] 2015-04-09 11:56
Of course it happens on S44 git, because I think I only added it on sweden...

**Comment by kanatohodets** [comment] 2015-04-09 12:50
ha, indeed! my bad, didn't notice that your change was on sweden.

**Comment by ashdnazg** [comment] 2015-05-26 15:26
Should be fixed here: https://github.com/spring1944/spring1944/commit/7f85ea9d5f9f8af23e335784b462273acb1fbea9

**Closed by ashdnazg** 2015-05-26 15:26 UTC
Labels: fixed-in-sweden
