### ISSUE TITLE
Mortar, Heavy Artillery and Hills

### ISSUE THREAD

**Issue by shibumi** [spring1944/spring1944#284] opened 2018-03-01 20:08 UTC
I just realized that rocket mortar can't attack when it is on a lower position than the target. This makes no sense.

Same applies for heavy japanese Ho-Ro artillery. When on much higher or lower position the Ho-Ro can't shoot.. this makes no sense as well..

**Comment by FLOZi** [comment] 2019-08-29 20:58
Same root cause as #324

**Comment by sanguinariojoe** [comment] 2020-09-30 14:10
And https://github.com/spring1944/spring1944/issues/323

I'm closing this issue

**Closed by sanguinariojoe** 2020-09-30 14:10 UTC
