### ISSUE TITLE
Create lua OO base classes for all other unit types

### ISSUE THREAD

**Issue by FLOZi** [spring1944/spring1944#53] opened 2014-11-09 17:50 UTC
A biggy, maybe inf first

**Comment by kanatohodets** [comment] 2015-03-12 14:39
this is done, right?

**Comment by Lowdive** [comment] 2015-03-12 22:37
* All unitdefs are now OO f0e4748252d795f617560ae2c32a0e3e32d6bb30
on sweden branch...

On Thu, Mar 12, 2015 at 8:39 AM, Ben Tyler <notifications@github.com> wrote:

> this is done, right?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spring1944/spring1944/issues/53#issuecomment-78492257>
> .
>



-- 
José Elí Santiago Rodríguez.
Disponibilidad de Horario.
<https://www.google.com/calendar/embed?src=elisantiago.4e%40gmail.com&ctz=America/Mexico_City&mode=Week>

**Comment by kanatohodets** [comment] 2015-05-22 09:54
finished, not a bug that needs checking, so going to close it. nice work floz!

**Closed by kanatohodets** 2015-05-22 09:54 UTC
Labels: fixed-in-sweden
